#ifndef SYLLABIFY_FR_H
#define SYLLABIFY_FR_H

/* Generated by cbindgen — regenerate with:
 *   cbindgen --config ffi/cbindgen.toml --crate syllabify-fr-ffi \
 *             --output ffi/include/syllabify_fr.h
 */

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Free a string previously returned by a syllabify_* function.
 * Passing NULL is a no-op.
 */
void syllabify_free(char *ptr);

/**
 * Syllabify a word, returning syllables joined by hyphens.
 *
 * Example: "chocolat" -> "cho-co-lat"
 *
 * Returns NULL on NULL input or invalid UTF-8.
 * The caller must free the result with syllabify_free().
 */
char *syllabify_syllables(const char *word);

/**
 * Syllabify full text, returning a JSON array of chunk objects.
 *
 * Each chunk is either {"kind":"word","syllables":["cho","co","lat"]} or
 * {"kind":"raw","text":" "}.
 *
 * Returns NULL on NULL input.
 * The caller must free the result with syllabify_free().
 */
char *syllabify_text_json(const char *text);

/**
 * Get phonemes for a word as a JSON array of [code, letters] pairs.
 *
 * Example: "chat" -> [["c","ch"],["V","a"],["c","t"]]
 *
 * Returns NULL on NULL input.
 * The caller must free the result with syllabify_free().
 */
char *syllabify_phonemes(const char *word);

/**
 * Render HTML for a single word with <span class="syl-a/b"> syllable spans.
 *
 * Returns NULL on NULL input.
 * The caller must free the result with syllabify_free().
 */
char *syllabify_render_word_html(const char *word);

/**
 * Render HTML for full text with syllable spans and liaison markers.
 *
 * Returns NULL on NULL input.
 * The caller must free the result with syllabify_free().
 */
char *syllabify_render_html(const char *text);

/**
 * Highlight confusable letters in `word` using a named preset.
 *
 * `preset` accepts "bdpq", "mnu", or "pir-pri".
 * `mode` accepts "inline" or "classes" (NULL = inline default).
 * On unknown preset the word is returned HTML-escaped without spans.
 *
 * Returns NULL on NULL `word` or `preset`, or on invalid UTF-8.
 * The caller must free the result with syllabify_free().
 */
char *syllabify_highlight_letters(const char *word, const char *preset, const char *mode);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* SYLLABIFY_FR_H */
